name: civilisation_creatif
version: '0.5'
main: fr.mattmunich.civilisation_creatif.Main
api-version: '1.21'
commands:
  minijeuxentrepotes:
    description: "§6§lCommande pour retourner sur le serveur principal!"
    usage: /mjep
    aliases:
      - servprincipal
      - servmain
      - mjep
      - lobby
  spawn:
    description: "§6§lCommande pour retourner au spawn du serveur !"
    usage: /spawn [world]
  xp:
    description: "§6§lCommande pour gérer l'XP d'un joueur !"
    usage: /xp <player> <add/remove/reset/get> [xpAmount]
    aliases:
      - exp
      - experience
  money:
    description: "§6§lCommande pour gérer l'argent d'un joueur !"
    usage: /money <player> <add/remove/reset/get> [moneyAmount]
    aliases:
      - argent
  rank:
    description: "§6§lCommande pour gérer le grade d'un joueur !"
    usage: /rank <player> <rank>
    aliases:
      - grade
  civilisation:
    description: "§6§lCommande du plugin !"
    usage: /civilisation [credits/reload]
  backup:
    description: "§6§lCommande pour faire une sauvegarde des mondes immédiatement !"
    usage: /backup
  territoire:
    description: "§6§lCommande pour gérer son territoire !"
    usage: /territoire
  warp:
    description: §6Commande pour se §5téléporter à un warp§6 :)
    usage: /warp <warpName>
  setwarp:
    description: §6Commande pour §5définir un warp ! §6(§cAdmin§4Cmd§6)
    usage: /setwarp <warpName> [permission]
  delwarp:
    description: §6Commande pour §5suprimer un warp ! §6(§cAdmin§4Cmd§6)
    usage: /delwarp <warpName>
  sethome:
    usage: /sethome <HomeName>
    description: §6Commande pour §5définir§6 un §5home §6:)
    aliases:
      - seth
  home:
    usage: /home <HomeName>
    description: §6Commande pour se §5téléporter §6à un §5home §6:)
    aliases:
      - h
  delhome:
    usage: /delhome <HomeName>
    description: §6Commande pour §5supprimer §6un §5home§6 :)
    aliases:
      - delh
